import { motion } from 'framer-motion'
import { Sparkles } from 'lucide-react'
import Screen from '../components/Screen'
import Header from '../components/Header'
import { NumberTicker } from '../components/NumberTicker'
import { useStore } from '../lib/store'
import { formatRelativeTime } from '../lib/mockData'

export default function Yield() {
  const lifetimeYieldCents = useStore((s) => s.lifetimeYieldCents)
  const transactions = useStore((s) => s.transactions)
  const yieldTxs = transactions.filter((t) => t.type === 'yield').slice(0, 6)

  return (
    <Screen transition="modal" className="min-h-screen flex flex-col px-6 pb-6">
      <Header title="EARNINGS" />

      {/* Hero — 3.33% APY lime card */}
      <motion.section
        initial={{ opacity: 0, y: 12 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.45 }}
        className="bg-lime border-[2px] border-ink rounded-[24px] shadow-ink-md p-5 mb-3"
      >
        <div className="flex items-center gap-1.5 mb-2">
          <span className="font-mono font-semibold text-[10px] uppercase tracking-[0.18em] text-ink/65">
            Your yield
          </span>
          <motion.span
            animate={{ opacity: [0.4, 1, 0.4] }}
            transition={{ duration: 1.6, repeat: Infinity }}
            className="w-1.5 h-1.5 rounded-full bg-ink ml-1"
          />
          <span className="font-mono font-semibold text-[9px] uppercase tracking-[0.14em] text-ink/65">
            Live
          </span>
        </div>

        <div className="flex items-baseline leading-[0.9] mb-1 numeric">
          <span
            className="font-numeric font-bold text-ink"
            style={{ fontSize: 80, letterSpacing: '-0.05em' }}
          >
            3.33
          </span>
          <span
            className="font-numeric font-bold text-ink ml-1"
            style={{ fontSize: 36, letterSpacing: '-0.04em' }}
          >
            %
          </span>
        </div>
        <div className="font-body text-[13px] text-ink-soft mt-1">
          APY · Compounds daily · No lock-up
        </div>
      </motion.section>

      {/* Lifetime card */}
      <motion.section
        initial={{ opacity: 0, y: 12 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.45, delay: 0.06 }}
        className="bg-paper-elevated border border-line rounded-[16px] p-4 mb-3"
      >
        <div className="font-mono font-semibold text-[10px] uppercase tracking-[0.18em] text-ink-muted mb-1">
          Lifetime earned
        </div>
        <NumberTicker
          valueCents={lifetimeYieldCents}
          duration={900}
          render={({ dollars, cents }) => (
            <div className="flex items-baseline leading-none numeric">
              <span className="font-numeric font-semibold text-ink-muted text-[18px] mr-0.5">
                $
              </span>
              <span className="font-numeric font-bold text-ink text-[32px] tracking-[-0.035em]">
                {dollars}
              </span>
              <span className="font-numeric font-semibold text-ink-muted text-[18px]">
                .{cents}
              </span>
            </div>
          )}
        />
        <div className="text-[12px] text-ink-muted mt-1.5">
          Compounds daily. Auto-deposits to your balance.
        </div>
      </motion.section>

      {/* How it works — dark ink card */}
      <motion.section
        initial={{ opacity: 0, y: 12 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.45, delay: 0.12 }}
        className="bg-ink rounded-[16px] p-4 mb-5 text-paper"
      >
        <div className="flex items-center gap-2 mb-3">
          <div className="w-5 h-5 rounded-full bg-lime flex items-center justify-center">
            <span className="font-mono font-bold text-[10px] text-ink">i</span>
          </div>
          <span className="font-display font-bold text-[15px] tracking-tight">How it works</span>
        </div>

        <ul className="space-y-2">
          {[
            'Your AUDD balance earns 3.33% APY automatically',
            'Yield drops once a day. No lock-up, no minimum',
            'Generated by Treasury-backed reserves on Solana',
          ].map((text, i) => (
            <li key={i} className="flex items-start gap-2.5">
              <span className="w-1.5 h-1.5 rounded-full bg-lime flex-shrink-0 mt-[7px]" />
              <span className="text-[13px] leading-[1.45] text-paper/90">{text}</span>
            </li>
          ))}
        </ul>
      </motion.section>

      {/* Recent payouts */}
      {yieldTxs.length > 0 && (
        <motion.section
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.45, delay: 0.18 }}
        >
          <div className="flex items-center justify-between mb-2.5">
            <h2 className="font-display font-bold text-[16px] tracking-tight">Recent payouts</h2>
            <span className="font-mono font-semibold text-[10px] uppercase tracking-[0.18em] text-ink-muted">
              Last 7 days
            </span>
          </div>

          <ul className="space-y-2">
            {yieldTxs.map((tx) => (
              <li
                key={tx.id}
                className="bg-paper-elevated border border-line rounded-[14px] px-4 py-3 flex items-center gap-3"
              >
                <div className="w-9 h-9 rounded-full bg-lime border-[1.5px] border-ink flex items-center justify-center flex-shrink-0">
                  <Sparkles size={13} strokeWidth={2.5} className="text-ink" />
                </div>
                <div className="flex-1 min-w-0">
                  <div className="font-display font-bold text-[13px] tracking-tight leading-[1.2]">
                    Daily yield
                  </div>
                  <div className="text-[11px] text-ink-muted leading-[1.3]">
                    {formatRelativeTime(tx.createdAt)}
                  </div>
                </div>
                <div className="font-numeric font-bold text-[14px] tracking-tight text-ink numeric">
                  +${(Math.abs(tx.amountCents) / 100).toFixed(2)}
                </div>
              </li>
            ))}
          </ul>
        </motion.section>
      )}
    </Screen>
  )
}
